// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCommand(arg1:string):Promise<string>;

export function ExecuteConnect(arg1:string):Promise<void>;

export function ExecuteMount(arg1:string):Promise<void>;

export function GetCustomers():Promise<Array<string>>;

export function GetMountHistory():Promise<Array<string>>;

export function GetVersion():Promise<string>;

export function HideWindow():Promise<void>;

export function RunMount(arg1:string):Promise<string>;

export function SaveMount(arg1:string):Promise<void>;

export function ShowConnectDialog():Promise<void>;

export function ShowMountDialog():Promise<void>;
