// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCommand(arg1) {
  return window['go']['main']['App']['ExecuteCommand'](arg1);
}

export function ExecuteConnect(arg1) {
  return window['go']['main']['App']['ExecuteConnect'](arg1);
}

export function ExecuteMount(arg1) {
  return window['go']['main']['App']['ExecuteMount'](arg1);
}

export function GetCustomers() {
  return window['go']['main']['App']['GetCustomers']();
}

export function GetMountHistory() {
  return window['go']['main']['App']['GetMountHistory']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function RunMount(arg1) {
  return window['go']['main']['App']['RunMount'](arg1);
}

export function SaveMount(arg1) {
  return window['go']['main']['App']['SaveMount'](arg1);
}

export function ShowConnectDialog() {
  return window['go']['main']['App']['ShowConnectDialog']();
}

export function ShowMountDialog() {
  return window['go']['main']['App']['ShowMountDialog']();
}
